/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mapping;

import org.junit.Test;
import static org.junit.Assert.*;

public class MapToCollectionTest {

    @Test public void testMapToCollection() {
        assertTrue(true);
    }
}